/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pdmnotes_PdmCrypt */

#ifndef _Included_com_pdmnotes_PdmCrypt
#define _Included_com_pdmnotes_PdmCrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pdmnotes_PdmCrypt
 * Method:    getHash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pdmnotes_PdmCrypt_getHash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
