THIS_DIR := $(call my-dir)

include $(REACT_ANDROID_DIR)/Android-prebuilt.mk

# If you wish to add a custom TurboModule or Fabric component in your app you
# will have to include the following autogenerated makefile.
include $(GENERATED_SRC_DIR)/codegen/jni/Android.mk
include $(CLEAR_VARS)

LOCAL_PATH := $(THIS_DIR)

# You can customize the name of your application .so file here.
LOCAL_MODULE := pdmnotes_appmodules

LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_SRC_FILES := $(wildcard $(LOCAL_PATH)/*.cpp)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)


# If you wish to add a custom TurboModule or Fabric component in your app you
# will have to uncomment those lines to include the generated source
# files from the codegen (placed in $(GENERATED_SRC_DIR)/codegen/jni)
#
# LOCAL_C_INCLUDES += $(GENERATED_SRC_DIR)/codegen/jni
# LOCAL_SRC_FILES += $(wildcard $(GENERATED_SRC_DIR)/codegen/jni/*.cpp)
# LOCAL_EXPORT_C_INCLUDES += $(GENERATED_SRC_DIR)/codegen/jni

# Here you should add any native library you wish to depend on.
LOCAL_SHARED_LIBRARIES := \
  libfabricjni \
  libfbjni \
  libfolly_runtime \
  libglog \
  libjsi \
  libreact_codegen_rncore \
  libreact_debug \
  libreact_nativemodule_core \
  libreact_render_componentregistry \
  libreact_render_core \
  libreact_render_debug \
  libreact_render_graphics \
  librrc_view \
  libruntimeexecutor \
  libturbomodulejsijni \
  libyoga

LOCAL_CFLAGS := -DLOG_TAG=\"ReactNative\" -fexceptions -frtti -std=c++17 -Wall -DLINUX -DWEB_RELEASE -DSINGLETHREADING -DWEB_RELEASE_LINUX_TEST

include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)

# # pdm files
#
# LOCAL_MODULE := cc20
# LOCAL_SRC_FILES := -I../pdm-crypt-module/src/app/pdm-crypt-module/src/include \
#                    -I../pdm-crypt-module/src/app/pdm-crypt-module/src/lib \
#                    -I../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/wasm \
#                    -I../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/cpp-mmf \
#                    -I../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/poly1305-donna-master \
#                    -I../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/ecc \
#                    -I../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/scrypt/include \
#                    -I../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/scrypt \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/cc20_file.cpp \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/sha3.cpp \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/cpp-mmf/memory_mapped_file.cpp \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/poly1305-donna-master/poly1305-donna.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/ecc/ecdh_curve25519.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/ecc/curve25519.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/ecc/fe25519.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/ecc/bigint.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/scrypt/src/hmac.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/scrypt/src/pbkdf2.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/scrypt/src/salsa20.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/scrypt/src/scrypt.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/empp.cpp \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/scrypt/src/sha256.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/lib/ec.cpp \
#                    ../java/com/pdmnotes/com_pdmnotes_PdmCrypt.c \
#                    ../pdm-crypt-module/src/app/pdm-crypt-module/src/cc20core/cc20_multi.cpp
# APP_CPPFLAGS := -fexceptions
# include $(BUILD_STATIC_LIBRARY)
